### ISSUE TITLE
Problem with UWP in Unity 5.5.1f

### ISSUE THREAD

**Issue by leonardomarquesdev** [Unity3dAzure/AppServices#4]
Table operations usually work in the editor. But not on my Windows Phone 10. Error occurs while trying to insert.

Should this plugin work on Windows Universal 10?

**Comment by deadlyfingers** [comment]
It should work as UWP app, but you have to be careful **not to use properties** (using the shorthand 'get' / 'set') in your JSON model as these will not work when running as Windows Store App. Rather **use fields** instead as shown in the [demo project models](https://github.com/Unity3dAzure/AppServicesDemo/blob/master/Assets/Scripts/DataModels/Highscore.cs). 

```c#
using System;
using Unity3dAzure.AppServices;

[Serializable]
public class Highscore : DataModel 
{
	public string username;
	public uint score;
}
```

Btw this example inherits the base `DataModel` which uses methods to get the system properties like id, date created, date updated, version and deleted:
https://github.com/Unity3dAzure/AppServices/blob/master/model/base/DataModel.cs

If this is not your issue please attach a snippet of your C# JSON model inline. Otherwise if this fixes the error, pls close the issue.

**Comment by leonardomarquesdev** [comment]
Thanks @deadlyfingers , one of the problems really was with the DataModel class.
